"use client";

import React, { createContext, useContext, useState } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.about": "Sobre Mí",
    "nav.services": "Servicios",
    "nav.projects": "Proyectos",
    "nav.contact": "Contacto",
    "hero.badge": "Diseñador & Desarrollador Frontend",
    "hero.title1": "CONSTRUYENDO EL",
    "hero.title2": "FUTURO DIGITAL",
    "hero.desc": "Transformo tus ideas en experiencias digitales de alto impacto que impulsan tu negocio. Especializado en diseño moderno, desarrollo web escalable y soluciones centradas en resultados.",
    "hero.cta1": "Ver Proyectos",
    "hero.cta2": "Contactar",
    "about.title": "Sobre Mí",
    "about.subtitle": "Fusionando creatividad y tecnología para dar vida a visiones digitales audaces.",
    "about.bio": "Biografía Profesional",
    "about.p1": "Soy un apasionado de la intersección entre el arte digital y la ingeniería de software. Mi enfoque se basa en romper los moldes tradicionales para crear experiencias web uniques.",
    "about.p2": "Desde el diseño de marca hasta el despliegue en la nube, manejo cada etapa del proceso con una mentalidad obsesionada con el detalle.",
    "about.exp": "Experiencia",
    "services.title": "Servicios Premium",
    "services.subtitle": "Soluciones digitales integrales diseñadas para conquistar el mañana.",
    "services.s1.title": "Diseño Web UI/UX",
    "services.s1.desc": "Diseños personalizados que combinan estética, funcionalidad y emoción.",
    "services.s2.title": "Desarrollo Web",
    "services.s2.desc": "Arquitecturas robustas y escalables construidas con las tecnologías más avanzadas.",
    "services.s3.title": "Diseño de Marca",
    "services.s3.desc": "Identidades visuales únicas que posicionan tu negocio en la vanguardia.",
    "services.s4.title": "Ciberseguridad",
    "services.s4.desc": "Protección integral para tus activos y datos de usuarios.",
    "services.s5.title": "Optimización SEO",
    "services.s5.desc": "Estrategias para dominar motores de búsqueda y atraer tráfico.",
    "services.s6.title": "Analítica Avanzada",
    "services.s6.desc": "Monitorización de datos para optimizar la conversión.",
    "process.title": "Mi Proceso Creativo",
    "process.subtitle": "De la idea al despliegue final siguiendo un flujo de trabajo optimizado.",
    "process.step1.title": "Investigación",
    "process.step1.desc": "Analizo requisitos para definir la arquitectura ideal.",
    "process.step2.title": "Diseño UX/UI",
    "process.step2.desc": "Creo prototipos visuales con estética moderna.",
    "process.step3.title": "Desarrollo",
    "process.step3.desc": "Transformo el diseño en código limpio y optimizado.",
    "process.step4.title": "Lanzamiento",
    "process.step4.desc": "Despliegue y optimización continua del rendimiento.",
    "projects.title": "Proyectos Destacados",
    "projects.subtitle": "Una selección de misiones digitales completadas con éxito.",
    "projects.filter.all": "Todos",
    "projects.visit": "Visitar Sitio",
    "projects.code": "Código",
    "skills.title": "Habilidades Técnicas",
    "skills.subtitle": "Mi arsenal tecnológico para conquistar el ciberespacio digital.",
    "experience.title": "Mi Evolución",
    "experience.subtitle": "Un recorrido por los hitos que me transformaron.",
    "experience.item1.title": "Finalización de Estudios",
    "experience.item1.company": "Fundamentos Académicos",
    "experience.item1.desc": "Cerré mi etapa de formación con curiosidad insaciable por la web.",
    "experience.item2.title": "Mi Primera Web",
    "experience.item2.company": "Proyecto Génesis",
    "experience.item2.desc": "Lancé mi primer sitio oficial. El código se volvió real.",
    "experience.item3.title": "Evolución y Proyectos",
    "experience.item3.company": "Crecimiento Autónomo",
    "experience.item3.desc": "Años de experimentación refinando mi estética y lógica.",
    "experience.item4.title": "Dominio Tecnológico",
    "experience.item4.company": "Estado Actual",
    "experience.item4.desc": "Foco en crear experiencias digitales inmersivas de alto nivel.",
    "testimonials.title": "Casos de Éxito",
    "testimonials.subtitle": "Lo que dicen mis clientes sobre la transformación de su presencia digital.",
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "Despeja tus dudas sobre el proceso de trabajo.",
    "faq.q1": "¿Cuánto tiempo toma desarrollar un sitio web?",
    "faq.a1": "Depende de la complejidad. Una landing page toma 1-2 semanas, una plataforma 1-3 meses.",
    "faq.q2": "¿Qué tecnologías utilizas?",
    "faq.a2": "Me especializo en Next.js, TypeScript, Tailwind CSS y Node.js/Supabase.",
    "faq.q3": "¿Ofreces servicios de mantenimiento?",
    "faq.a3": "Sí, ofrezco planes de soporte mensual para asegurar seguridad y rendimiento.",
    "faq.q4": "¿Puedes ayudar con el diseño?",
    "faq.a4": "¡Por supuesto! Como diseñador UI/UX, te guío desde la idea al prototipo.",
    "contact.title": "Contacto",
    "contact.subtitle": "¿Listo para iniciar tu próxima misión digital? Envíame un mensaje.",
    "contact.info": "Información de Enlace",
    "contact.social": "Redes Sociales",
    "contact.name": "Nombre Completo",
    "contact.email": "Correo Electrónico",
    "contact.phone": "Teléfono / WhatsApp",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.send": "Enviar Mensaje",
    "contact.sending": "Enviando...",
    "footer.made": "Hecho con",
    "footer.by": "por Raúl Ariel",
    "footer.slogan": "Construyendo el futuro una línea de código a la vez",
  },
  en: {
    "nav.home": "Home",
    "nav.about": "About Me",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.contact": "Contact",
    "hero.badge": "Designer & Frontend Developer",
    "hero.title1": "BUILDING THE",
    "hero.title2": "DIGITAL FUTURE",
    "hero.desc": "I transform your ideas into high-impact digital experiences that drive your business. Specialized in modern design, scalable web development, and result-oriented solutions.",
    "hero.cta1": "View Projects",
    "hero.cta2": "Contact Me",
    "about.title": "About Me",
    "about.subtitle": "Merging creativity and technology to bring bold digital visions to life.",
    "about.bio": "Professional Biography",
    "about.p1": "I am passionate about the intersection of digital art and software engineering. My approach is based on breaking traditional molds to create unique web experiences.",
    "about.p2": "From brand design to cloud deployment, I handle every stage of the process with a detail-obsessed mindset.",
    "about.exp": "Experience",
    "services.title": "Premium Services",
    "services.subtitle": "Comprehensive digital solutions designed to conquer tomorrow.",
    "services.s1.title": "UI/UX Web Design",
    "services.s1.desc": "Custom designs that combine aesthetics, functionality, and emotion.",
    "services.s2.title": "Web Development",
    "services.s2.desc": "Robust and scalable architectures built with the most advanced technologies.",
    "services.s3.title": "Brand Design",
    "services.s3.desc": "Unique visual identities that position your business at the forefront.",
    "services.s4.title": "Cybersecurity",
    "services.s4.desc": "Comprehensive protection for your assets and user data.",
    "services.s5.title": "SEO Optimization",
    "services.s5.desc": "Strategies to dominate search engines and attract traffic.",
    "services.s6.title": "Advanced Analytics",
    "services.s6.desc": "Data monitoring to optimize conversion behavior.",
    "process.title": "My Creative Process",
    "process.subtitle": "From idea to final deployment following an optimized workflow.",
    "process.step1.title": "Research",
    "process.step1.desc": "I analyze requirements to define the ideal architecture.",
    "process.step2.title": "UI/UX Design",
    "process.step2.desc": "I create visual prototypes with modern aesthetics.",
    "process.step3.title": "Development",
    "process.step3.desc": "I transform design into clean and optimized code.",
    "process.step4.title": "Launch",
    "process.step4.desc": "Continuous deployment and performance optimization.",
    "projects.title": "Featured Projects",
    "projects.subtitle": "A selection of digital missions successfully completed.",
    "projects.filter.all": "All",
    "projects.visit": "Visit Site",
    "projects.code": "Code",
    "skills.title": "Technical Skills",
    "skills.subtitle": "My technological arsenal to conquer the digital cyberspace.",
    "experience.title": "My Evolution",
    "experience.subtitle": "A journey through the milestones that transformed me.",
    "experience.item1.title": "Graduation",
    "experience.item1.company": "Academic Foundations",
    "experience.item1.desc": "I finished my training with insatiable curiosity about the web.",
    "experience.item2.title": "My First Website",
    "experience.item2.company": "Genesis Project",
    "experience.item2.desc": "I launched my first official site. Code became real.",
    "experience.item3.title": "Evolution & Projects",
    "experience.item3.company": "Autonomous Growth",
    "experience.item3.desc": "Years of experimentation refining my aesthetics and logic.",
    "experience.item4.title": "Tech Mastery",
    "experience.item4.company": "Current State",
    "experience.item4.desc": "Focus on creating high-level immersive digital experiences.",
    "testimonials.title": "Success Stories",
    "testimonials.subtitle": "What my clients say about the transformation of their digital presence.",
    "faq.title": "FAQ",
    "faq.subtitle": "Clear your doubts about the work process and collaboration.",
    "faq.q1": "How long does it take to develop a website?",
    "faq.a1": "It depends on complexity. A landing page takes 1-2 weeks, a platform 1-3 months.",
    "faq.q2": "What technologies do you use?",
    "faq.a2": "I specialize in Next.js, TypeScript, Tailwind CSS and Node.js/Supabase.",
    "faq.q3": "Do you offer maintenance services?",
    "faq.a3": "Yes, I offer monthly support plans to ensure security and performance.",
    "faq.q4": "Can you help with the design?",
    "faq.a4": "Of course! As a UI/UX designer, I guide you from idea to prototype.",
    "contact.title": "Contact",
    "contact.subtitle": "Ready to start your next digital mission? Send me a message.",
    "contact.info": "Link Information",
    "contact.social": "Social Media",
    "contact.name": "Full Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone / WhatsApp",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "footer.made": "Made with",
    "footer.by": "by Raúl Ariel",
    "footer.slogan": "Building the future one line of code at a time",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  // Set default language to English ("en")
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};