// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://akwlgcghwgrulymouckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrd2xnY2dod2dydWx5bW91Y2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MDMwNTUsImV4cCI6MjA4ODI3OTA1NX0.XgfGl6PKuR_fZpAZ8Lbze7a7oKREDzK1BfyrnR9no00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);